// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NicFWebApp.Pages.Shared.Classes;

#nullable disable

namespace NicFWebApp.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20240623200746_AddExperienceAndTask")]
    partial class AddExperienceAndTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("NicFWebApp.Pages.Shared.Classes.Experience", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("NicFWebApp.Pages.Shared.Classes.Task", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Experienceid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Experienceid");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("NicFWebApp.Pages.Shared.Classes.Task", b =>
                {
                    b.HasOne("NicFWebApp.Pages.Shared.Classes.Experience", null)
                        .WithMany("Tasks")
                        .HasForeignKey("Experienceid");
                });

            modelBuilder.Entity("NicFWebApp.Pages.Shared.Classes.Experience", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
